### ISSUE TITLE
Some class missing "Partial"

### ISSUE THREAD

**Issue by atifwaqar** [per-samuelsson/AppShip#7]
![image](https://cloud.githubusercontent.com/assets/4388707/11931771/7e5dbb52-a7f0-11e5-9d72-09203c34e6dc.png)

**Comment by per-samuelsson** [comment]
@atifsheikh 

Ah, damn, sorry. My bad. I forgot we haven't made any release of that yet. If you run it with the latest nightly build of Starcounter it will work, but we have to wait for a nightly until we can build it. 

Or I will include the current version of [`Partial.cs`](https://github.com/Starcounter/Starcounter/blob/develop/src/Starcounter/Partial.cs) in this repo. Let me consider this for a second.

**Comment by per-samuelsson** [comment]
> Or I will include the current version of [`Partial.cs`](https://github.com/Starcounter/Starcounter/blob/develop/src/Starcounter/Partial.cs) in this repo. Let me consider this for a second.

I've done so, pushed here: 0b163f5ae4c05811a93cf5f37416bd5ded95a7b2. You should just have to pull and build again. Let me know if it solves it @atifsheikh.

**Comment by miyconst** [comment]
By public release, do you mean stable build? The nightly channel has `Partial` class for quite some time.

**Comment by per-samuelsson** [comment]
> By public release, do you mean stable build? The nightly channel has `Partial` class for quite some time.

Yes, I do. I consider the stable ones the "public" ones, since I presume most of our users would use the stable ones by default.

**Comment by per-samuelsson** [comment]
I would consider the public releases those that is normally fetched from [here](http://starcounter.io/download/).

**Comment by atifwaqar** [comment]
i have another error now 

![image](https://cloud.githubusercontent.com/assets/4388707/11976705/600d23f4-a97b-11e5-8e41-30c70046093e.png)

**Comment by atifwaqar** [comment]
i changed it to 
public string ImplicitStandaloneTitle = Application.Current.Name; 

and started the exe, lets see what happens now ;)

**Comment by atifwaqar** [comment]
ok it worked, no where should i send the zipped folder?
also, is my Data and Code Safe by sending this dump?

**Comment by per-samuelsson** [comment]
> ok it worked, no where should i send the zipped folder?

Great. Really appreciate your effort here!

We don't really have an established routine for this just yet, so its kind of case by case ad hoc. But if you are willing to share that application and data, we can hopefully assist you better, and we'll be sure to treat it in a confidental way.

Drop me a line on `per [at] starcounter [dot] [com]`, and provide me with a way to contact you (like a mail address), and I'll suggest a way for you to share that zip with me.

Merry xmas! :santa: :smile:

**Comment by atifwaqar** [comment]
I have sent you a mail.
Merry xmas! :santa:
